"""
Mapa EDITÁVEL de ingrediente -> emoji.

Como funciona o `emoji_for(nome)`:
  1. busca exata pelo nome normalizado em EMOJI_EXACT;
  2. se não houver, procura uma palavra-chave contida no nome (KEYWORD_RULES),
     o que captura variações ("chicken breast", "smoked chicken" -> 🍗);
  3. fallback genérico -> 🥄 (GENERIC).

Para ajustar o mapeamento, basta editar os dicionários abaixo — nenhuma outra
parte do código precisa mudar.
"""

GENERIC = "🥄"

# ----------------------------------------------------------- correspondência exata
# Chave = nome normalizado (lowercase). Edite à vontade.
EMOJI_EXACT = {
    "milk": "🥛",
    "egg": "🥚",
    "eggs": "🥚",
    "butter": "🧈",
    "cheese": "🧀",
    "parmesan": "🧀",
    "salt": "🧂",
    "sea salt": "🧂",
    "pepper": "🌶️",
    "black pepper": "🌶️",
    "chilli": "🌶️",
    "chili": "🌶️",
    "red chilli": "🌶️",
    "garlic": "🧄",
    "garlic clove": "🧄",
    "onion": "🧅",
    "red onion": "🧅",
    "spring onions": "🧅",
    "shallots": "🧅",
    "tomato": "🍅",
    "tomatoes": "🍅",
    "chopped tomatoes": "🍅",
    "potato": "🥔",
    "potatoes": "🥔",
    "carrot": "🥕",
    "carrots": "🥕",
    "corn": "🌽",
    "sweetcorn": "🌽",
    "broccoli": "🥦",
    "cucumber": "🥒",
    "lettuce": "🥬",
    "spinach": "🥬",
    "kale": "🥬",
    "cabbage": "🥬",
    "mushroom": "🍄",
    "mushrooms": "🍄",
    "avocado": "🥑",
    "eggplant": "🍆",
    "aubergine": "🍆",
    "lemon": "🍋",
    "lime": "🍋",
    "lemon juice": "🍋",
    "lemons": "🍋",
    "apple": "🍎",
    "apples": "🍎",
    "banana": "🍌",
    "bananas": "🍌",
    "strawberries": "🍓",
    "strawberry": "🍓",
    "blueberries": "🫐",
    "grapes": "🍇",
    "peach": "🍑",
    "pineapple": "🍍",
    "coconut": "🥥",
    "coconut milk": "🥥",
    "cherries": "🍒",
    "orange": "🍊",
    "mango": "🥭",
    "ginger": "🫚",
    "ground ginger": "🫚",
    "bread": "🍞",
    "breadcrumbs": "🍞",
    "flour": "🌾",
    "plain flour": "🌾",
    "self-raising flour": "🌾",
    "rice": "🍚",
    "basmati rice": "🍚",
    "brown rice": "🍚",
    "pasta": "🍝",
    "spaghetti": "🍝",
    "noodles": "🍜",
    "macaroni": "🍝",
    "honey": "🍯",
    "sugar": "🍬",
    "brown sugar": "🍬",
    "caster sugar": "🍬",
    "icing sugar": "🍬",
    "chocolate": "🍫",
    "dark chocolate": "🍫",
    "cocoa": "🍫",
    "salt and pepper": "🧂",
    "olive oil": "🫒",
    "olives": "🫒",
    "vegetable oil": "🛢️",
    "sunflower oil": "🛢️",
    "oil": "🛢️",
    "water": "💧",
    "wine": "🍷",
    "red wine": "🍷",
    "white wine": "🍷",
    "beer": "🍺",
    "coffee": "☕",
    "tea": "🍵",
    "chicken": "🍗",
    "chicken breast": "🍗",
    "chicken breasts": "🍗",
    "chicken thighs": "🍗",
    "turkey": "🦃",
    "duck": "🦆",
    "beef": "🥩",
    "minced beef": "🥩",
    "beef mince": "🥩",
    "steak": "🥩",
    "pork": "🥓",
    "bacon": "🥓",
    "ham": "🍖",
    "sausages": "🌭",
    "sausage": "🌭",
    "lamb": "🍖",
    "fish": "🐟",
    "salmon": "🐟",
    "tuna": "🐟",
    "cod": "🐟",
    "prawns": "🦐",
    "shrimp": "🦐",
    "crab": "🦀",
    "squid": "🦑",
    "shrimps": "🦐",
    "peas": "🫛",
    "green peas": "🫛",
    "beans": "🫘",
    "kidney beans": "🫘",
    "black beans": "🫘",
    "chickpeas": "🫘",
    "lentils": "🫘",
    "peanuts": "🥜",
    "peanut butter": "🥜",
    "almonds": "🌰",
    "walnuts": "🌰",
    "cashew nuts": "🌰",
    "nuts": "🌰",
    "cinnamon": "🤎",
    "vanilla": "🍦",
    "vanilla extract": "🍦",
    "cream": "🍦",
    "double cream": "🍦",
    "yogurt": "🥛",
    "yoghurt": "🥛",
    "bay leaf": "🌿",
    "basil": "🌿",
    "parsley": "🌿",
    "coriander": "🌿",
    "cilantro": "🌿",
    "mint": "🌿",
    "rosemary": "🌿",
    "thyme": "🌿",
    "oregano": "🌿",
    "dill": "🌿",
    "paprika": "🌶️",
    "cumin": "🟤",
    "turmeric": "🟡",
    "curry powder": "🟡",
    "soy sauce": "🍶",
    "vinegar": "🧴",
    "saffron": "🌸",
    "redcurrants": "🍒",
    "currants": "🍇",
    "raisins": "🍇",
    "baking powder": "🧁",
    "baking soda": "🧁",
    "yeast": "🍞",
    "tofu": "🧊",
    "mustard": "🟡",
    "mayonnaise": "🥚",
    "ketchup": "🍅",
}

# ----------------------------------------- fallback por PALAVRA-CHAVE (substring)
# Ordem importa: a primeira regra cujo termo apareça no nome vence.
KEYWORD_RULES = [
    ("chicken", "🍗"),
    ("beef", "🥩"),
    ("steak", "🥩"),
    ("pork", "🥓"),
    ("bacon", "🥓"),
    ("lamb", "🍖"),
    ("ham", "🍖"),
    ("sausage", "🌭"),
    ("turkey", "🦃"),
    ("duck", "🦆"),
    ("salmon", "🐟"),
    ("tuna", "🐟"),
    ("cod", "🐟"),
    ("fish", "🐟"),
    ("prawn", "🦐"),
    ("shrimp", "🦐"),
    ("crab", "🦀"),
    ("cheese", "🧀"),
    ("milk", "🥛"),
    ("cream", "🍦"),
    ("butter", "🧈"),
    ("egg", "🥚"),
    ("garlic", "🧄"),
    ("onion", "🧅"),
    ("tomato", "🍅"),
    ("potato", "🥔"),
    ("carrot", "🥕"),
    ("mushroom", "🍄"),
    ("pepper", "🌶️"),
    ("chilli", "🌶️"),
    ("chili", "🌶️"),
    ("lemon", "🍋"),
    ("lime", "🍋"),
    ("apple", "🍎"),
    ("banana", "🍌"),
    ("berry", "🫐"),
    ("berries", "🫐"),
    ("coconut", "🥥"),
    ("chocolate", "🍫"),
    ("cocoa", "🍫"),
    ("sugar", "🍬"),
    ("honey", "🍯"),
    ("flour", "🌾"),
    ("rice", "🍚"),
    ("pasta", "🍝"),
    ("noodle", "🍜"),
    ("spaghetti", "🍝"),
    ("bread", "🍞"),
    ("oil", "🛢️"),
    ("wine", "🍷"),
    ("beer", "🍺"),
    ("vanilla", "🍦"),
    ("bean", "🫘"),
    ("pea", "🫛"),
    ("nut", "🌰"),
    ("salt", "🧂"),
    ("leaf", "🌿"),
    ("herb", "🌿"),
    ("spice", "🌶️"),
    ("sauce", "🥫"),
    ("stock", "🥫"),
    ("water", "💧"),
]


def emoji_for(name):
    """Devolve o emoji do ingrediente (nome JÁ normalizado), com fallback 🥄."""
    if name in EMOJI_EXACT:
        return EMOJI_EXACT[name]
    for keyword, emoji in KEYWORD_RULES:
        if keyword in name:
            return emoji
    return GENERIC
